"""Post

Revision ID: 041d148843e0
Revises: 1e12476a27ea
Create Date: 2020-06-10 17:40:22.069966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041d148843e0'
down_revision = '1e12476a27ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id', 'author'),
    sa.UniqueConstraint('url')
    )
    op.create_table('post_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_type')
    op.drop_table('post')
    # ### end Alembic commands ###
