"""Adding photo into user

Revision ID: 1e12476a27ea
Revises: f2205abe233b
Create Date: 2020-06-08 20:11:59.023738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e12476a27ea'
down_revision = 'f2205abe233b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_photo', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('photo_path', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo_path')
    op.drop_column('user', 'has_photo')
    # ### end Alembic commands ###
