"""Post corrections

Revision ID: 470d834b3e95
Revises: eb9a57c2cfaa
Create Date: 2020-06-10 20:21:08.774452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '470d834b3e95'
down_revision = 'eb9a57c2cfaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=140), nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=140), nullable=True),
    sa.Column('has_photo_header', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('has_photo_preview', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('photo_header_path', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('photo_preview_path', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('title_preview_text', mysql.VARCHAR(length=128), nullable=True),
    sa.CheckConstraint('(`has_photo_header` in (0,1))', name='post_chk_1'),
    sa.CheckConstraint('(`has_photo_preview` in (0,1))', name='post_chk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('url', 'post', ['url'], unique=True)
    # ### end Alembic commands ###
