"""Post

Revision ID: 9b95eac58ada
Revises: 8b5ce7cb5f69
Create Date: 2020-06-10 18:39:42.524745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b95eac58ada'
down_revision = '8b5ce7cb5f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('has_photo_header', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('has_photo_preview', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('photo_header_path', sa.String(length=256), nullable=True))
    op.add_column('post', sa.Column('photo_preview_path', sa.String(length=256), nullable=True))
    op.add_column('post', sa.Column('title_preview_text', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title_preview_text')
    op.drop_column('post', 'photo_preview_path')
    op.drop_column('post', 'photo_header_path')
    op.drop_column('post', 'has_photo_preview')
    op.drop_column('post', 'has_photo_header')
    # ### end Alembic commands ###
