"""Post corrections

Revision ID: a3422a36275c
Revises: 5d7aebe89df6
Create Date: 2020-06-10 20:23:10.191765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3422a36275c'
down_revision = '5d7aebe89df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url', table_name='post')
    op.drop_column('post', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('url', mysql.VARCHAR(length=140), nullable=True))
    op.create_index('url', 'post', ['url'], unique=True)
    # ### end Alembic commands ###
