"""Post corrections

Revision ID: eb9a57c2cfaa
Revises: 9b95eac58ada
Create Date: 2020-06-10 19:51:14.725163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb9a57c2cfaa'
down_revision = '9b95eac58ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'author',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'author',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
