"""deleting surname

Revision ID: f2205abe233b
Revises: fd9bdfb375a5
Create Date: 2020-06-08 16:43:34.994122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2205abe233b'
down_revision = 'fd9bdfb375a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('surname', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
